apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  labels:
    app: web1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: zorothehunter/web1
        ports:
        - containerPort: 5500

---
apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  selector:
    app: web1
  ports:
    - port: 80
      targetPort: 5500
  type: ClusterIP
