apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3
  labels:
    app: web3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web3
  template:
    metadata:
      labels:
        app: web3
    spec:
      containers:
      - name: web3
        image: zorothehunter/web3
        ports:
        - containerPort: 5502

---
apiVersion: v1
kind: Service
metadata:
  name: web3-service
spec:
  selector:
    app: web3
  ports:
    - port: 80
      targetPort: 5502
  type: ClusterIP
